
# Copyright (C) 2006-2024 The Analog System Compiler project

# This file was automatically generated by the ASysC compiler. Don't modify it.


import math
import circuit_base
from circuit_base import circuit_base, element

class circuit( circuit_base ):

	def __init__(self):
		super().__init__()
		self.IC_VCC = element('IC_VCC')
		self.IC_SW_I = element('IC_SW_I')
		self.IC_IOUT = element('IC_IOUT')
		self.C1_I = element('C1_I')
		self.V1_I = element('V1_I')
		self.RA_I = element('RA_I')
		self.RB_I = element('RB_I')
		self.C1_U = element('C1_U')
		self.IC_UTRIG = element('IC_UTRIG')
		self.RB_U = element('RB_U')
		self.P2_U = element('P2_U')
		self.RA_U = element('RA_U')
		self.IC_SW_U = element('IC_SW_U')
		self.IC_UOUT2 = element('IC_UOUT2')
		self.IC_UOUT = element('IC_UOUT')
		self.IC_UIN2 = element('IC_UIN2')
		self.IC_UIN1 = element('IC_UIN1')
		self.P1_U = element('P1_U')
		self.IC_UTRESH = element('IC_UTRESH')
		self.V1_U = element('V1_U')

	def step(self):
		self._setc(self.IC_VCC,0)
		self._setc(self.IC_SW_I,0)
		self._setc(self.IC_IOUT,0)
		self._setc(self.C1_I,0)
		self._setc(self.V1_I,0)
		self._setc(self.RA_I,0)
		self._setc(self.RB_I,0)
		self._setc(self.C1_U,0)
		self._setc(self.IC_UTRIG,0)
		self._setc(self.RB_U,0)
		self._setc(self.P2_U,0)
		self._setc(self.RA_U,0)
		self._setc(self.IC_SW_U,0)
		self._setc(self.IC_UOUT2,DIVIDE_BY_ZERO_ERROR())
		self._setc(self.IC_UOUT,DIVIDE_BY_ZERO_ERROR())
		self._setc(self.IC_UIN2,0)
		self._setc(self.IC_UIN1,0)
		self._setc(self.P1_U,DIVIDE_BY_ZERO_ERROR())
		self._setc(self.IC_UTRESH,0)
		self._setc(self.V1_U,0)

