L'abre qui cache la matrice.

* Introduction
    Il existe de nombreux simulateurs electronique libres  et on citera par exemple les plus connus:
        - Clones Spice (pspce, ngspice)
        - Qucs
        - Xyce

        What is ADMS?
ADMS ("Automatic Device Model Synthesizer") is an open-source Verilog-A translator. It reads a Verilog-A input file and produces a complex internal data structure representing the module. It then processes a set of XML templates written in an XSLT-based templating language called ADMST. These user-provided templates access the internal ADMS data structure, and can be written to emit code in any desired language targeting any desired simulator.

A l'origine, ces simulateurs intégraient des modèles de composnats codés en "dur", puis se sont vous ajouter de nouvelles fonctionnalités pour pouvoir acceuillri des composants défins par les utilisateurs eux-même au travers d'équations symboliques.
Citons par exemple le cas des simulatuers Xyce et Qucs qui intègrent chacun AMDS qui est un logiciel qui traduit une description en Verilog-a à être traduite dans un autre language de programmation.
Par l'intermédiare d'ADMS, il a été possible d'ajouter à ces simulateur des descriptions de composnants en langage symbolique. L'avantage des descritptions de ystèmes ert sous systèmes en lagage symblique est
que vous pouvez étendre un solver de sysèmes electriques en solveur des sytèmes de mécanique des fluides, biologie...

Ces simulateurs utilisent des solveurs qui vont placer les équations dnas des matrices puis les résoudre. Etant donné que dans un circuit électronique, les noeuds sont rarement connectés à plus de 3 branches,
on obtient dans la majorité des cas des matrices qu'on appelle des matrices creuses ( "sparse matrices" en Anglais). Avec des algorthimes avancés pour résoudre ces cas de figure.

Dans cet article, je vous propose de simuler vos circuits électroniques avec une approche radcialement différente de ce qui a été fait jusqu'à présent, c'est à dire qu'on va supporter nativement les équaltions symboliques,
ce qui va vous permettre de créer des composants avec les focntions mathématiques usuelles et résoudre ces équations sans passer par une résolution matricielle. Sans utiliser ADMS.
Et comment faire clea? tout simplement avec ce qu'on appelle un "CAS", un "Computer Algebra System" en Français: "Calcul formel" ou "Calcul Symbolique"

* Quest-ce qu'un CAS?
Un système de calcul formel (computer algebra system ou CAS en anglais) est un logiciel qui facilite le calcul symbolique. La partie principale de ce système est la manipulation des expressions mathématiques sous leur forme symbolique.

* asysc
ASysC est un CAS léger qui a été initiallement écrit par l'auteur de cet article sur les bancs de la prépa il y a de ça plusieurs années (plusieurs décennies même!) et qui a lentement évolué
pour pouvoir simuler des composants éléctroniques.
A proprement parler, ASysC ne simule pas le système électronique mais va assembler les équations des différents composnants en un système d'équation qu'il va ensuite résoudre symboliquement et constituer un ensemble d'équations.
ASysC contient les règles de résolution de systèmes éléctriques, cad les lois de Kirchhoff.


* exemple CAS
* Application à l'electronique
    - Déclaration d'une résistance
    - Déclaration d'un condensateur
    - Déclaration d'une self

* Analyses
** DC
** AC
** AC avec paramètres
** Transient

= Conclusion 

- Verilog AMS
- IBIS
- Cocotb

https://xyce.sandia.gov/documentation-tutorials/
