
# Copyright (C) 2006-2024 The Analog System Compiler project

# This file was automatically generated by the ASysC compiler. Don't modify it.


import math
import circuit_base
from circuit_base import circuit_base, element

class circuit( circuit_base ):

	def __init__(self):
		super().__init__()
		self.D_U = element('D_U')
		self.V_U = element('V_U')
		self.V_I = element('V_I')
		self.R_I = element('R_I')
		self.D_I = element('D_I')
		self.R_U = element('R_U')

	def compute_t(self):
		self._setc(self.D_U, (5*math.sin(23687.0505626*self._time())-200*(1e-15*((1-self._last(self.D_U)/0.026)*math.exp(self._last(self.D_U)/0.026)-1)))/(1+(200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026))
		self._setc(self.V_U, ((1+(200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026)*(5*math.sin(23687.0505626*self._time())))/(1+(200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026))
		self._setc(self.V_I, -((1e-15*((1-self._last(self.D_U)/0.026)*math.exp(self._last(self.D_U)/0.026)-1)+((1e-15*math.exp(self._last(self.D_U)/0.026))*(5*math.sin(23687.0505626*self._time())))/0.026)/((200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026+1)))
		self._setc(self.R_I, (1e-15*((1-self._last(self.D_U)/0.026)*math.exp(self._last(self.D_U)/0.026)-1)+((1e-15*math.exp(self._last(self.D_U)/0.026))*(5*math.sin(23687.0505626*self._time())))/0.026)/(1+((1e-15*math.exp(self._last(self.D_U)/0.026))*200)/0.026))
		self._setc(self.D_I, (1e-15*((1-self._last(self.D_U)/0.026)*math.exp(self._last(self.D_U)/0.026)-1)+((1e-15*math.exp(self._last(self.D_U)/0.026))*(5*math.sin(23687.0505626*self._time())))/0.026)/((200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026+1))
		self._setc(self.R_U, (200*(1e-15*((1-self._last(self.D_U)/0.026)*math.exp(self._last(self.D_U)/0.026)-1))+((200*(1e-15*math.exp(self._last(self.D_U)/0.026)))*(5*math.sin(23687.0505626*self._time())))/0.026)/((200*(1e-15*math.exp(self._last(self.D_U)/0.026)))/0.026+1))

