name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: build
      run: make clean build

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
